use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.3'

target 'SKYKitChat_Example' do
  pod 'SKYKitChat', :path => '../'
end

target 'SKYKitChat_Tests' do
  pod 'SKYKitChat', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'OHHTTPStubs'
end

target 'Swift Example' do
  pod 'SKYKitChat', :path => '../'
  pod 'SKYKitChat/UI', :path => '../'
  pod 'Kingfisher', '~> 3.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end
