use_frameworks!

target 'SKYKitChat_Example' do
  pod 'SKYKitChat', :path => '../'

  target 'SKYKitChat_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end

target 'Swift Example' do
  pod 'SKYKitChat', :path => '../'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
      end
  end
end
