use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

#https://github.com/CocoaPods/CocoaPods/issues/4370#issuecomment-284075060
install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => false
platform :ios, '8.3'

target 'SKYKitChat_Example' do
  pod 'SKYKitChat', :path => '../'
end

target 'SKYKitChat_Tests' do
  pod 'SKYKitChat', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'OHHTTPStubs'
end

target 'Swift Example' do
  pod 'SKYKitChat', :path => '../'
  pod 'SKYKitChat/UI', :path => '../'
  pod 'Kingfisher', '~> 4.0'
end

# The SWIFT_VERSION setting is inserted into pod targets, otherwise, the
# SKPhotoBrowser pod complains when compiling. 
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
      end
  end
end
